
name: Build Debian Package On PR

on:
  pull_request:
    paths:
      - 'debian/changelog'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro: [buster,bullseye]
        arch: [armhf,arm64]
    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Debian package
        uses: danielmundi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-profiler_package
          path: ${{ steps.build-debian-package.outputs.deb-package }}