
name: Build Debian Packages
on:
  push:
    paths:
      - 'debian/changelog'
  pull_request:
    paths:
      - 'debian/changelog'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro: [buster]
        arch: [armhf]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Debian package
        uses: danielmundi/sbuild-debian-package@sbuild
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}
      - name: Upload package
        uses: danielmundi/upload-gemfury@main
        with:
          package-name: ${{ steps.build_debian_package.outputs.deb-package }}
          gemfury-username: ${GEMFURY_NAME}
          gemfury-token: ${GEMFURY_TOKEN}