name: Packagecloud Build CI

on:
  push:
    branches:
      - main
    paths:
      - 'debian/changelog'

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    strategy:
      fail-fast: false
      matrix:
        distro: [buster,bullseye]
        arch: [armhf,arm64]

    environment: PACKAGECLOUD

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sbuild for ${{ matrix.distro }} ${{ matrix.arch }}
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Archive artifacts and upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-profiler-${{ matrix.distro }}-${{ matrix.arch }}
          path: ${{ steps.build-debian-package.outputs.deb-package }}

      - name: Upload package to packagecloud
        uses: danielmundi/upload-packagecloud@main
        with:
          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
          packagecloud-username: wlanpi
          packagecloud-repo: dev
          packagecloud-distrib: raspbian/${{ matrix.distro }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
  
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          message: '{"channel":"CFN3PMQD8","text": "${{ github.repository }}@${{ github.ref_name }} <${{ github.event.commits[0].url }}/checks|${{ github.workflow }}> *${{ job.status }}* (${{ matrix.distro }}\${{ matrix.arch }}) --- <${{ github.event.commits[0].url }}|${{ github.event.commits[0].message }}> by ${{ github.event.commits[0].author.name }}"}'
        if: always()
        uses: pullreminders/slack-action@master
        with:
          args: ${{ toJSON(env.message) }}